spring.application.name=travel

jwt.secret=<jwt.secret(StringType)>
jwt.expiration=<expTime Type mill>

spring.datasource.url=<YourMysqlDataBaseUrl>
spring.datasource.username=<account>
spring.datasource.password=<password>

mybatis-plus.configuration.map-underscore-to-camel-case=false


spring.data.redis.host=<YourRedisUrl>
spring.data.redis.port=<RedisPort>
spring.data.redis.password=<RedisPassword(Can be empty)>
spring.cache.type=redis

spring.mail.host=<verifyCodeSendEmailHost>
spring.mail.port=<emailPort>
spring.mail.username=<Your emailAddress>
spring.mail.password=<FromYourEmailServer>
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
